{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "senainetuno.serviceAccountName" . }}
  labels:
{{ include "senainetuno.labels" . | indent 4 }}
{{- end -}}
